const Words = [
  [
    "Fam",
    "Glow up",
    "Cancel Culture",
    "Stan",
    "Dank",
    "Ghosting",
    "Salty",
    "Big Yikes",
    "Boujee",
    "Finna",
    "Cap",
    "High-key",
    "Cheugy",
    "Camp",
    "Snack",
    "Sip tea",
    "Take several seats",
    "Drip",
    "Bop",
    "Sheesh",
    "Iykyk",
    "Living rent free",
    "Hits different",
    "Bet",
    "Vibe check",
    "Periodt",
    "Catch these hands",
    "Drag",
    "Finesse",
    "I’m weak",
    "Main character",
    "Sis",
    "Sending me",
    "Slaps",
    "Bussin’",
    "Sus",
    "Snatched",
    "Guap",
    "Smol",
    "This ain’t it, chief",
    "Extra",
    "Clapback",
    "GOAT",
    "fit",
    "fire",
    "thow shade",
    "go off",
  ],
  [
    "Threads",
    "A gas",
    "Hacked off",
    "Flip a wig",
    "Groovy",
    "Lay a patch",
    "Square",
    "What's your bag",
    "Padiddle",
    "Dropped a dime",
    "Moo juice",
    "wig chop",
    "Drag",
    "Kicks",
    "Chrome dome",
    "Scratch",
    "Cool Cat",
    "Don't flip your wig",
    "razz my berries",
    "a big tickle",
    "wet rag",
    "come on, snake, let's rattle",
    "What's your bag",
    "fink",
    "Meanwhile, back at the ranch",
    "Stop dipping in my Kool-Aid",
    "what a fry",
    "grody",
  ],
];

export default Words;
